pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = "https://index.docker.io/v1/"
        DOCKER_REPO = "prameela0/appbackend"   // <-- change this to your backend repo
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/prameela-namala/aws-devops-capstone-project.git'
            }
        }

        stage('Build Docker Image') {
    steps {
        sh """
            echo "Building backend Docker image..."
            docker build -t ${DOCKER_REPO}:${IMAGE_TAG} api/
        """
    }
}

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds',
                                                 usernameVariable: 'USERNAME',
                                                 passwordVariable: 'PASSWORD')]) {
                    sh """
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                    echo "Pushing backend Docker image..."
                    docker push ${DOCKER_REPO}:${IMAGE_TAG}
                """
            }
        }
    }

    post {
        success {
            echo "Backend image pushed: ${DOCKER_REPO}:${IMAGE_TAG}"
        }
        failure {
            echo "Backend pipeline failed!"
        }
    }
}